name: evolphy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  fluentui_system_icons: ^1.1.238
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1C202A"
  image: "images/SplashLogo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: fonts/outfit/Outfit-Regular.ttf
        - asset: fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/outfit/Outfit-Bold.ttf
          weight: 700
